### PR TITLE
Support relative fader action

### PR DESCRIPTION
**Pull request by istnv**
Add variables for channel level dB and %
Add missing DCA set fader level
Add fader 'adjust' action for all channels: +/- configurable number of steps.
Add variable for channel 'name' from mixer scribble strip
Add feedback for channel 'color' from mixer scribble strip

### CODE REVIEW

**Comment by krocheck** [comment]
Tested?

**Comment by istnv** [comment]
> Tested?

As much as possible on a single X18.

**Comment by istnv** [comment]
This also covers #13

**Comment by dseehof** [comment]
Is this now implemented as part of the commit on the 27th of July?

**Comment by McHauge** [comment]
> Is this now implemented as part of the commit on the 27th of July?

yes this should be included in current build, might not be in the 2.1 release, but should be in all recent 2.1.1 beta builds.

**Pull request merged**
