### PR TITLE
V3.0

### PR DESCRIPTION
**Pull request by istnv**
Updated for Version 3

### CODE REVIEW

**Comment by Mozoloa** [comment]
Getting this error in a loop when trying it out on **Companion 3.0.0+5697-beta-77be33d9**

```
error: node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'osc' imported from E:\Professional\Empire Media Science\Projects\Companion\companion-module-behringer-xair\index.js
    at new NodeError (node:internal/errors:399:5)
    at packageResolve (node:internal/modules/esm/resolve:889:9)
    at moduleResolve (node:internal/modules/esm/resolve:938:20)
    at defaultResolve (node:internal/modules/esm/resolve:1153:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v18.14.2
```

**Comment by istnv** [comment]
> Getting this error in a loop when trying it out on **Companion 3.0.0+5697-beta-77be33d9**
> 
> ```
> error: node:internal/errors:490
>     ErrorCaptureStackTrace(err);
>     ^
> 
> Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'osc' imported from E:\Professional\Empire Media Science\Projects\Companion\companion-module-behringer-xair\index.js
>     at new NodeError (node:internal/errors:399:5)
>     at packageResolve (node:internal/modules/esm/resolve:889:9)
>     at moduleResolve (node:internal/modules/esm/resolve:938:20)
>     at defaultResolve (node:internal/modules/esm/resolve:1153:11)
>     at nextResolve (node:internal/modules/esm/loader:163:28)
>     at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
>     at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
>     at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
>     at link (node:internal/modules/esm/module_job:76:36) {
>   code: 'ERR_MODULE_NOT_FOUND'
> }
> 
> Node.js v18.14.2
> ```

**Comment by Mozoloa** [comment]
I just did it and the error still pops. I also tried npm install, full wipe of the folder then full restart of companion but the error is still here

**Comment by istnv** [comment]
The `OSC` module was not in the project dependencies. 
Re-fetch the repository.

**Comment by Mozoloa** [comment]
Alright this worked ! Also it didn't seem to connect once I entered the IP and saved, I had to restart the connection for it to go through the sync

**Comment by istnv** [comment]
Pushed a fix for that.
> Alright this worked ! Also it didn't seem to connect once I entered the IP and saved, I had to restart the connection for it to go through the sync

**Pull request merged**
