### PR TITLE
Collect list of XAir units on network

### PR DESCRIPTION
**Pull request by istnv**
Scans for list of mixers on network.
Creates a drop-down list for config options.
If sync times-out with no response, automatically re-configure the IP address if mixer with same name is located.
Should enable equivalent of issue #43

### CODE REVIEW

**Comment by dnmeid** [comment]
I know one user who connects to a bunch of sites thru a VPN tunnel and controls XAirs at the far end. Since the VPN in this case is a TUN type, he won't be able to find the XAirs, because the IPs are not in the same subnet.
Can you make the dropdown allowCustom, so you can enter an IP, which is not found automatically?

**Comment by istnv** [comment]
It is not yet feature complete, I can only torture the IP on my unit so much.
The original IP value is still available and will be used first.
I was going to add a switch to turn off scanning after some other testing.

**Comment by istnv** [comment]
Has option to enable network scan (defaults to off)
Moved some internal status variables to clear in `init` since `configUpdated` may point to a different unit/host.

**Comment by istnv** [comment]
Adds feature #47

**Comment by istnv** [comment]
Includes fix for #59

**Pull request merged**
