### PR TITLE
Addition of Channel Mute Variables

### PR DESCRIPTION
**Pull request by Boguinhos**
Added Channel Mute Variables

First time ever doing this, sorry if i am doing something wrong.

Added Mute state for channel strips for being able to be used with triggers.

### CODE REVIEW

**Comment by istnv** [comment]
I am currently in the process of changing some of the feedback functions to booleans that will cover this.

**Comment by Boguinhos** [comment]
I have read about changing some feedback to booleans before but i did not understand exactly how can those booleans be used with the trigger functionality. Can you summarise some insight?

**Comment by istnv** [comment]
Feedback is a new option for Triggers. When set up, you can run an action when a feedback (mute) is On or Off. You get the functionality without adding more clutter to the variable list.

**Comment by Boguinhos** [comment]
Thanks. I found it strange that feedbacks were not availabe on triggers on the latest beta builds of companion, only variables, but maybe i’m doin something wrong. When can this be expected to be a stable build?

**Comment by istnv** [comment]
Companion core has feedback triggers available for modules to use, however, the XAir feedbacks need to be converted. Not all of the feedback options (such as channel 'color from console') need updating. 
I am putting together the list of useful ones and working on it this week.

**Comment by Boguinhos** [comment]
Even if you managed to do it this week it would not mean that it would be available even as a beta anytime soon, would it?

**Comment by istnv** [comment]
I should have it submitted by the weekend. After that, it depends on when the core developers including the changes. I've also added some snapshot control (#33)

**Comment by McHauge** [comment]
@Boguinhos the core devs usually update modules 2-3 times a week, when asked, but sometimes they might miss It and it takes a bit longer, but within 2-5 days is the normal max. But keep in mind they only do if someone request's it on Slack :)

but a stable build would not be anytime soon, as 2.1.3 is still "new" so my bet would be September or something like that, but a 2.2.0 beta version could be ready within a few days after @istnv has looked at it and send off a request on slack. Hope that sheds some light on the process.

**Comment by Boguinhos** [comment]
It really does! Thank you both for the insight. I'm not much of a programmer but i was willing to try and help :P maybe someday i'll be able to make my own module for my tally lights :)
Thanks again

**Comment by krocheck** [comment]
Can someone close this or let me know if it should be merged after conflicts are handled?

**Comment by istnv** [comment]
This was a patch to expose mute status as a variable to enable use with a trigger. Another update (#36) converts the existing mute feedback to the newer boolean type and provides this functionality.

**Comment by McHauge** [comment]
@istnv so we can close this? or?

**Comment by istnv** [comment]
Equivalent features implemented in #36

**Pull request closed without merging**
